[build]
  # Diretório de build do frontend
  publish = "public"
  # Diretório das Netlify Functions
  functions = "functions"

[functions]
  # Exemplo de configuração, pode ser omitido se a configuração padrão for suficiente
  node_bundler = "esbuild"

# Redirecionamento de CORS (apenas para teste, a função já resolve)
# O redirecionamento pode ser útil para o Netlify Function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/sptrans-proxy"
  status = 200
