[build]
  # Diretório de build do frontend
  publish = "public"
  # Diretório das Netlify Functions
  functions = "functions"

# Redirecionamento de /api/* para a Netlify Function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/sptrans-proxy"
  status = 200
